from dataclasses import dataclass


@dataclass
class Case:
    name: str           # full case name, e.g. "People v. O.J. Simpson (1995)"
    charges: str        # what the defendant is charged with
    background: str     # context about the case and parties involved
    description: str    # facts presented at trial
    known_verdict: str  # "guilty" or "not_guilty" the real-world outcome


# ---------------------------------------------------------------------------
# Case definitions
# ---------------------------------------------------------------------------

TAX_EVASION = Case(
    name="United States v. Defendant (1931)",
    charges="Tax evasion five counts of willful failure to pay federal income taxes",
    known_verdict="guilty",
    background=(
        "The defendant, a 32-year-old organized crime figure widely regarded as the "
        "most powerful underworld boss in a major American city, was indicted in 1931 "
        "on twenty-two counts of federal income tax evasion covering the years 1925 "
        "through 1929. Federal investigators could not prosecute the defendant for "
        "the underlying criminal enterprises bootlegging, illegal gambling, and "
        "prostitution because witnesses were too intimidated to testify and physical "
        "evidence was routinely destroyed. Instead, a special IRS task force spent "
        "three years reconstructing the defendant's finances using the 'net expenditures' "
        "method: totaling every documented purchase, payment, and cash outlay to prove "
        "the defendant had received and spent substantial income that was never reported "
        "to the government. The defendant had never filed a federal income tax return "
        "for any of the years in question, and no bank accounts were held in the "
        "defendant's name. The prosecution relied heavily on the testimony of two "
        "bookkeepers from the defendant's gambling operations who agreed to cooperate "
        "with the government after being granted limited immunity."
    ),
    description=(
        "The government's theory was that income derived from illegal sources is "
        "nonetheless taxable under federal law, and that the defendant's lavish "
        "lifestyle and large cash payments proved the receipt of substantial unreported "
        "income. The IRS estimated the defendant owed approximately $215,000 in unpaid "
        "taxes equivalent to several million dollars today."
        "\n\nPROSECUTION EVIDENCE: Two cooperating bookkeepers from the defendant's "
        "gambling houses testified to the cash flow they personally recorded, identifying "
        "the defendant as the ultimate recipient of net profits. Documented expenditures "
        "introduced at trial included: a $100,000 cash payment for a Miami estate, "
        "tailored suits purchased in bulk at prices far exceeding an ordinary wage, "
        "hotel bills for extended stays in luxury suites paid in cash, and payroll "
        "records for dozens of personal staff. Western Union telegrams showed the "
        "defendant sending and receiving large sums across state lines. A cashier at "
        "a horse-racing establishment testified the defendant regularly placed and "
        "collected bets exceeding tens of thousands of dollars per visit. The government "
        "argued the sheer volume of cash expenditures was irreconcilable with any "
        "legitimate reported income."
        "\n\nDEFENSE EVIDENCE: The defense argued that no direct evidence linked the "
        "defendant personally to any specific receipt of income every transaction "
        "was in cash and nothing was in the defendant's name. Defense counsel contended "
        "that the expenditures could have been funded by non-taxable gifts or loans "
        "from associates, none of whom were called to testify. The two cooperating "
        "bookkeepers were challenged as having accepted immunity deals, giving them "
        "strong incentive to overstate the defendant's role. The defense also raised "
        "a jurisdictional argument: a prior meeting between a government attorney and "
        "the defendant's representative had allegedly produced an informal agreement "
        "that the defendant would plead to minor charges in exchange for no prison "
        "time a deal the government denied making but which the defense argued "
        "constituted prosecutorial bad faith."
        "\n\nSTATISTICAL CONTEXT: The 'net expenditures' method of proving unreported "
        "income has been upheld by federal courts but is inherently circumstantial  "
        "it infers income from spending rather than tracing funds directly. Legal "
        "scholars have noted that the method places the burden on defendants to explain "
        "the source of every large expenditure, which critics argue effectively shifts "
        "the presumption of innocence. Conviction rates in federal tax evasion trials "
        "during this era exceeded 80%, and juries were known to be receptive to "
        "arguments framing tax evasion as a civic duty violation."
    ),
)

PERJURY = Case(
    name="United States v. Defendant (1998)",
    charges=(
        "Perjury before a federal grand jury and obstruction of justice in connection "
        "with a sworn deposition given in a federal civil lawsuit"
    ),
    known_verdict="not_guilty",
    background=(
        "The defendant, a 52-year-old sitting head of the federal executive branch, "
        "was the subject of a multi-year independent counsel investigation that began "
        "as an inquiry into a real-estate venture from a decade earlier and expanded "
        "to encompass several unrelated matters. The investigation ultimately focused "
        "on sworn statements the defendant gave in January 1998 during a deposition in "
        "a federal civil lawsuit brought by a former state employee, in which the "
        "defendant denied having had a sexual relationship with a younger subordinate "
        "who worked at the same federal workplace. After a confidante of the subordinate "
        "secretly recorded conversations in which the subordinate described the "
        "relationship in detail and turned the recordings over to investigators, the "
        "independent counsel obtained immunity for the subordinate and compelled her "
        "grand jury testimony. The defendant subsequently appeared before a federal "
        "grand jury in August 1998 and again denied or qualified key facts about the "
        "relationship under oath. A 445-page report from the independent counsel laid "
        "out grounds for impeachment, and the lower chamber of the legislature voted "
        "two articles of impeachment perjury before the grand jury and obstruction of "
        "justice. The matter then proceeded to a trial in the upper chamber of the "
        "legislature, which under the constitution sits as the trier of fact and law "
        "for impeachments of federal executive officers. Conviction required a two-"
        "thirds supermajority of the 100 members."
    ),
    description=(
        "The proceeding was not a criminal trial in an ordinary court but a constitutional "
        "removal proceeding. However, the underlying allegations were treated as criminal "
        "in substance: the chamber acting as the prosecution presented evidence and "
        "called for a verdict of guilt on each article. The threshold question was "
        "whether the defendant knowingly made materially false statements under oath "
        "and whether the defendant took affirmative steps to conceal the truth from "
        "investigators."
        "\n\nPROSECUTION EVIDENCE: The subordinate's grand jury testimony, given under "
        "an immunity agreement, described the relationship in granular detail and "
        "directly contradicted the defendant's sworn deposition answers. A physical "
        "garment belonging to the subordinate was forensically tested and found to "
        "contain biological material genetically matched to the defendant at a frequency "
        "exceeding 1 in 7.87 trillion. Detailed gift records, building entry logs, and "
        "phone records corroborated the timing and frequency of meetings the defendant "
        "had denied. The defendant's personal secretary testified that the defendant "
        "had asked her to retrieve gifts from the subordinate after the civil lawsuit "
        "had begun, which prosecutors framed as obstruction. A close associate of the "
        "defendant testified that the defendant had suggested the subordinate could "
        "sign a false affidavit denying the relationship. The defendant's grand jury "
        "answers were played in full, with prosecutors highlighting moments where the "
        "defendant relied on narrow definitional readings of common terms to deny "
        "conduct that ordinary listeners would understand to fall within those terms."
        "\n\nDEFENSE EVIDENCE: The defense argued that the deposition answers, while "
        "evasive and embarrassing, were technically truthful under the strained "
        "definitions the defendant had been given to work with at the deposition. "
        "Defense counsel emphasized that the underlying civil lawsuit was later "
        "dismissed on summary judgment, making any false statements within it "
        "immaterial to the outcome of that case a required element for federal "
        "perjury. The defense further argued that retrieving personal gifts and "
        "discussing potential affidavits did not rise to the level of obstruction "
        "absent proof of corrupt intent, and that no witness was prevented from "
        "testifying or coerced into changing testimony. On the broader constitutional "
        "question, the defense argued that even if every factual allegation were "
        "accepted, the conduct concerned a private matter and did not constitute "
        "the 'high crimes and misdemeanors' standard required for removal of a "
        "sitting head of the executive. Polling introduced in argument showed sustained "
        "majority public approval of the defendant's job performance throughout the "
        "proceedings."
        "\n\nSTATISTICAL CONTEXT: This was only the second time in the nation's history "
        "that a sitting head of the executive branch had been impeached by the lower "
        "chamber and tried by the upper chamber. The previous such trial, more than "
        "130 years earlier, also ended in acquittal by a single vote. Federal perjury "
        "convictions in ordinary criminal courts during this period had a conviction "
        "rate above 70%, but those cases lacked the political-trial structure of an "
        "impeachment proceeding, in which the triers of fact were elected officials "
        "voting along largely partisan lines. The final votes were 45-55 on the perjury "
        "article and 50-50 on the obstruction article, both falling short of the 67 "
        "votes required for conviction. Legal scholars have since debated whether the "
        "acquittal reflected a genuine evidentiary judgment, a political judgment about "
        "the proportionality of removal, or a partisan judgment driven by chamber "
        "composition."
    ),
)

DEFAMATION = Case(
    name="Defendant v. Counter-Defendant (2022)",
    charges=(
        "Civil defamation three statements alleged to have been made with actual "
        "malice and to have caused reputational and economic damage to the plaintiff"
    ),
    known_verdict="guilty",
    background=(
        "The plaintiff, a 58-year-old internationally recognized film actor, sued "
        "the defendant, a 36-year-old film actor and his former spouse, for defamation "
        "in a state circuit court. The lawsuit centered on a 2018 opinion piece "
        "published by the defendant in a major national newspaper, in which the "
        "defendant described herself as a 'public figure representing domestic abuse' "
        "and referenced 'two years' during which she 'felt the full force of our "
        "culture's wrath for women who speak out.' The article did not name the "
        "plaintiff. The plaintiff argued the article nonetheless clearly referred "
        "to him given the timing it was published shortly after their highly "
        "publicized divorce and the defendant's prior public allegations during "
        "the divorce proceedings. The plaintiff sought $50 million in damages, "
        "alleging the article had cost him major film roles, including a leading "
        "franchise role he had held for nearly two decades. The defendant filed a "
        "$100 million counterclaim alleging that statements made by the plaintiff's "
        "attorney calling her allegations a 'hoax' were themselves defamatory. The "
        "couple had married in 2015 and divorced in 2017 after roughly fifteen months "
        "of marriage. The defendant had previously obtained a temporary restraining "
        "order against the plaintiff in 2016, supported by a photograph showing a "
        "mark on her face. The trial was televised in full and watched by tens of "
        "millions of viewers, with substantial commentary on social media throughout "
        "the six-week proceeding."
    ),
    description=(
        "Under the governing state's defamation law, the plaintiff was required to "
        "prove by a preponderance of evidence that (1) the statements at issue were "
        "false, (2) they were 'of and concerning' him, (3) they were defamatory in "
        "meaning, and (4) they were published with 'actual malice' meaning the "
        "defendant knew they were false or acted with reckless disregard for their "
        "truth. Because the plaintiff is a public figure, the actual malice standard "
        "applied. The case turned on whether the underlying allegations of mistreatment "
        "during the marriage were truthful: if they were, the article was protected "
        "speech; if they were fabricated or substantially exaggerated, it was actionable."
        "\n\nPLAINTIFF EVIDENCE: The plaintiff testified for several days and denied "
        "ever initiating physical aggression toward the defendant, asserting instead "
        "that the defendant had been the aggressor throughout the marriage. Audio "
        "recordings made by the plaintiff during the marriage were played to the jury, "
        "in which the defendant could be heard acknowledging hitting the plaintiff "
        "and mocking him for suggesting that a man could be a victim of partner "
        "mistreatment 'tell the world... see how many people believe or side with "
        "you.' Photographs were introduced showing injuries to the plaintiff including "
        "a severed fingertip, which the plaintiff testified resulted from a thrown "
        "bottle during an argument in Australia in 2015. Multiple household staff "
        "and security personnel testified they had personally observed marks on the "
        "plaintiff but had never observed marks on the defendant in real time. A "
        "forensic psychologist retained by the plaintiff testified that the defendant "
        "did not meet diagnostic criteria for post-traumatic stress disorder and "
        "instead presented with traits consistent with borderline and histrionic "
        "personality disorders. The plaintiff's prior agents and producers testified "
        "that he had been formally dropped from a major film franchise within days "
        "of the article's publication, costing him a contract reportedly worth more "
        "than $22 million. A forensic image analyst testified that photographs the "
        "defendant submitted showing facial injuries appeared to have been altered "
        "or staged."
        "\n\nDEFENDANT EVIDENCE: The defendant testified across multiple days "
        "describing a pattern of escalating mistreatment during the marriage that she "
        "attributed to the plaintiff's substance use, and described in graphic detail "
        "an incident in Australia in which she alleged the plaintiff had assaulted "
        "her over the course of three days. She produced photographs taken contemporaneously "
        "showing facial bruising and a swollen lip, and introduced therapy records from "
        "a marriage counselor in 2015 describing 'mutual abuse.' A friend of the "
        "defendant testified to having observed injuries on the defendant on multiple "
        "occasions and to having helped her cover them with makeup before public "
        "appearances. A clinical psychologist retained by the defendant testified that "
        "the defendant met diagnostic criteria for post-traumatic stress disorder "
        "stemming from the relationship. The defendant pointed to text messages from "
        "the plaintiff to a third party in which the plaintiff wrote graphic threats "
        "about her, which the plaintiff acknowledged at trial were his own words but "
        "characterized as venting rather than serious. The defendant also pointed to "
        "the plaintiff's own admitted history of substance use during the marriage "
        "as corroborating her account of his behavior, and emphasized that her 2018 "
        "article had not named the plaintiff and had been a general statement about "
        "her experience as a public advocate."
        "\n\nSTATISTICAL CONTEXT: Defamation suits brought by public figures succeed "
        "at a substantially lower rate than those brought by private individuals, "
        "because of the heightened 'actual malice' standard imposed by Supreme Court "
        "precedent. Estimates from media-law scholars place the success rate of such "
        "suits at trial below 15%. The trial was unusual in that it was televised "
        "in full, in a jurisdiction that permitted cameras in civil court, and "
        "generated tens of billions of social-media impressions during proceedings "
        "an environment some legal scholars argued risked influencing the seven-member "
        "jury despite admonitions against external exposure. Surveys conducted during "
        "trial showed sharply divided public opinion along demographic and ideological "
        "lines, with male and younger respondents more likely to credit the plaintiff's "
        "account and female and older respondents more likely to credit the defendant's. "
        "The jury ultimately found in favor of the plaintiff on all three challenged "
        "statements, awarding $10 million in compensatory damages and $5 million in "
        "punitive damages, the latter reduced to the state cap of $350,000. The jury "
        "also found in favor of the defendant on one of three statements in her "
        "counterclaim, awarding her $2 million."
    ),
)
FRAUD = Case(
    name="United States v. Defendant (2010)",
    charges=(
        "Federal corruption twenty-four counts including wire fraud, racketeering "
        "conspiracy, attempted extortion, conspiracy to solicit bribes, and making "
        "false statements to federal agents"
    ),
    known_verdict="not_guilty",
    background=(
        "The defendant, a 53-year-old two-term governor of a major Midwestern state, "
        "was arrested at his home in December 2008 by federal agents executing a "
        "warrant tied to a multi-year investigation of corruption in state government. "
        "The lead allegation concerned the defendant's authority, under the state "
        "constitution, to appoint a replacement to fill a recently vacated federal "
        "legislative seat the seat left open when its previous occupant won election "
        "to higher federal office. Federal prosecutors alleged that the defendant "
        "had attempted to leverage this appointment power for personal gain, exploring "
        "in conversations with aides and intermediaries whether the seat could be "
        "exchanged for a cabinet position, a private-sector job for himself or his "
        "spouse, campaign contributions, or appointment to a non-profit board. "
        "Beyond the appointment matter, the indictment described a broader pattern "
        "of alleged 'pay to play' conduct over the defendant's two terms in office, "
        "including alleged shakedowns of a children's hospital executive seeking a "
        "rate increase, a horse-racing track owner seeking favorable legislation, and "
        "a road-building executive seeking a state contract. Federal investigators "
        "had obtained court-authorized wiretaps on the defendant's home and campaign "
        "office phones, capturing approximately 500 hours of recorded conversations "
        "over roughly six weeks before the arrest. The defendant was impeached and "
        "removed from office by the state legislature in January 2009, before the "
        "criminal trial commenced. A separate co-defendant, the defendant's brother, "
        "was tried alongside him on related counts."
    ),
    description=(
        "The trial lasted approximately ten weeks and produced more than 130 hours "
        "of played-back recordings. The central legal question on the appointment "
        "counts was whether the defendant's recorded conversations crossed the line "
        "from ordinary political horse-trading the routine exchange of appointments, "
        "endorsements, and policy concessions that characterizes American politics "
        "into a criminal solicitation of personal benefit in exchange for an official "
        "act. On the broader counts, the question was whether specific official acts "
        "had been corruptly tied to specific demands for contributions or favors."
        "\n\nPROSECUTION EVIDENCE: The government's case rested heavily on the wiretap "
        "recordings. Jurors heard the defendant repeatedly describe the legislative "
        "appointment as a 'thing of value' that he was reluctant to give away 'for "
        "nothing,' including a recorded statement using a profanity-laced description "
        "of the seat as 'expletive golden' and another in which the defendant said "
        "'I'm not giving it up for expletive nothing.' Multiple aides and former "
        "advisers testified for the prosecution under cooperation agreements, "
        "describing meetings in which the defendant explored what could be obtained "
        "in exchange for the appointment. The defendant's former chief of staff "
        "testified to having delivered messages on the defendant's behalf to "
        "intermediaries close to the incoming federal administration. On the "
        "shakedown counts, executives from the hospital, racing, and construction "
        "industries testified that they had felt explicit or implicit pressure to "
        "make political contributions in proximity to pending official actions. "
        "Documentary evidence showed contribution checks dated within days of state "
        "actions favorable to the contributors. The prosecution argued the wiretaps "
        "removed any doubt about the defendant's intent: the recordings were the "
        "defendant's own words, captured in real time, with no opportunity for "
        "post-hoc revision."
        "\n\nDEFENSE EVIDENCE: The defendant did not testify in the first trial, a "
        "tactical decision his counsel later said they regretted. The defense argued "
        "that the recordings captured rambling, unfocused, and often profane "
        "brainstorming sessions in which the defendant explored many possibilities "
        "out loud but never actually executed any corrupt agreement. Defense counsel "
        "emphasized that the seat was never in fact sold no exchange ever occurred, "
        "no money or job ever changed hands, and the defendant was arrested before "
        "any appointment was made. The defense argued that exploring whether a "
        "political appointment could be traded for a cabinet position or a private-"
        "sector job is constitutionally protected political negotiation, not "
        "extortion. On the shakedown counts, the defense argued that proximity in "
        "time between contributions and official actions is endemic to American "
        "politics and that no contributor had testified to a direct quid-pro-quo "
        "demand. Defense counsel emphasized that the cooperating witnesses had "
        "received non-prosecution agreements that gave them strong incentives to "
        "frame ambiguous conversations as corrupt. On the false-statements count, "
        "the defense conceded that the defendant had told federal agents he kept his "
        "campaign work separate from his official duties, but argued this was an "
        "expression of intent rather than a verifiable factual claim."
        "\n\nSTATISTICAL CONTEXT: Federal corruption prosecutions of sitting or recent "
        "state governors have a high conviction rate historically above 85% when "
        "they reach trial. However, public-corruption law in this era was in flux: "
        "the Supreme Court would, in cases decided shortly after this trial, "
        "substantially narrow the federal 'honest services' fraud statute that "
        "underlay several of the counts. Legal scholars have noted that the line "
        "between criminal extortion and constitutionally protected political "
        "logrolling is contested, particularly where the alleged 'thing of value' "
        "is itself a political appointment that is universally understood to be "
        "exchanged for political support. After approximately fourteen days of "
        "deliberation, the jury reported it was hopelessly deadlocked on twenty-three "
        "of the twenty-four counts. The judge declared a mistrial on those counts. "
        "The jury convicted the defendant on a single count of making false "
        "statements to federal agents. The government announced within hours that "
        "it would retry the deadlocked counts. A retrial in 2011 resulted in "
        "convictions on seventeen counts and a fourteen-year prison sentence; the "
        "sentence was later commuted by a sitting head of the federal executive "
        "branch in 2020, after the defendant had served roughly eight years."
    ),
)
LARCENY = Case(
    name="State v. Defendant (2004)",
    charges=(
        "Grand larceny in the first degree, securities fraud, conspiracy, falsifying "
        "business records, and enterprise corruption thirty-eight counts in total "
        "alleging the defendant looted approximately $600 million from the publicly "
        "traded conglomerate he led as chief executive"
    ),
    known_verdict="not_guilty",
    background=(
        "The defendant, a 57-year-old chief executive officer of one of the largest "
        "publicly traded industrial conglomerates in the country, was indicted by a "
        "state grand jury along with the company's former chief financial officer on "
        "charges arising from a multi-year internal investigation into executive "
        "compensation. The conglomerate, which had grown through aggressive acquisition "
        "into a roughly $36 billion company employing more than 200,000 people, had "
        "removed the defendant from his position in 2002 after public reporting "
        "revealed he had used company funds to pay personal sales-tax obligations on "
        "fine-art purchases. Subsequent internal review allegedly uncovered a far "
        "broader pattern: roughly $150 million in unauthorized bonuses and forgiven "
        "loans paid to the defendant and his co-defendant, and roughly $430 million "
        "in additional gains from allegedly fraudulent stock sales preceded by "
        "misleading disclosures to investors. The state's theory was that the "
        "defendant and the co-defendant had used compensation programs nominally "
        "approved by the company's compensation committee, but had concealed the "
        "true scale of the disbursements from the full board and from shareholders "
        "by routing them through obscure accounting categories and by characterizing "
        "non-arm's-length loan forgiveness as routine business expense. Heavily "
        "publicized aspects of the case included a $2 million birthday celebration "
        "for the defendant's spouse held on a Mediterranean island and partially "
        "billed to the company, and roughly $30 million in apartment renovations "
        "including widely circulated reporting on a single $6,000 shower curtain. "
        "The first trial began in September 2003 and ran for approximately six "
        "months."
    ),
    description=(
        "The central legal question was not whether the defendant had received the "
        "payments at issue this was largely undisputed but whether the defendant "
        "had taken them with criminal intent. Under the governing state's larceny "
        "statute, the prosecution had to prove the defendant believed at the time "
        "he received the payments that he was not entitled to them. The defense "
        "theory was the opposite: that the defendant believed every payment had "
        "been duly authorized by the appropriate corporate body and was therefore "
        "lawful compensation, however generous it may have appeared in retrospect."
        "\n\nPROSECUTION EVIDENCE: The state called more than two dozen witnesses, "
        "including former members of the company's compensation committee, internal "
        "auditors, and outside accountants. Compensation committee members testified "
        "that they had never approved many of the bonus payments at issue, and that "
        "the defendant had used a program nominally tied to the completion of "
        "specific corporate transactions to pay himself bonuses for transactions "
        "that had not in fact occurred or that had been initiated under the prior "
        "chief executive. Documents introduced at trial showed loan-forgiveness "
        "entries booked to obscure ledger accounts under descriptions inconsistent "
        "with their true character. The state introduced evidence that the defendant "
        "had personally directed staff to pay personal expenses including the "
        "spouse's birthday celebration and apartment renovations from corporate "
        "accounts, then to record those payments in ways that obscured their "
        "personal nature. The state also introduced evidence of large stock sales "
        "by both defendants in the months preceding negative disclosures about the "
        "company's financial position, arguing the defendants had timed sales to "
        "avoid losses they knew the public did not yet appreciate. Several witnesses "
        "testified that the defendant had instructed them to keep specific "
        "compensation arrangements out of formal board minutes. The state argued "
        "the cumulative pattern dozens of unauthorized bonuses, concealed loan "
        "forgiveness, personal expenses billed to the company, and timed stock "
        "sales could not be reconciled with the defense's account of a chief "
        "executive who simply trusted his subordinates and his compensation "
        "committee."
        "\n\nDEFENSE EVIDENCE: The defendant testified in his own defense over "
        "approximately eight days, an unusual choice for a white-collar defendant. "
        "He acknowledged receiving every payment at issue and acknowledged the "
        "personal nature of the renovation and celebration expenses. His defense "
        "was that all of the payments had been approved by the company's "
        "compensation committee, by its general counsel, or by a senior corporate "
        "officer with apparent authority to approve them, and that he had relied "
        "in good faith on these approvals. Defense counsel argued that the bonus "
        "program at issue had been approved by the board years earlier and that "
        "the defendant had reasonably interpreted its scope to cover the payments "
        "he received. On the renovation and celebration expenses, the defense "
        "argued these were properly characterized as part of a relocation and "
        "executive-perquisite package the company had agreed to provide. The "
        "defense emphasized that no payment had been hidden from the company's "
        "external auditors, who had reviewed and certified the company's financial "
        "statements throughout the period. On the stock-sale counts, the defense "
        "argued the sales had been pre-scheduled under standard executive trading "
        "plans designed precisely to avoid the appearance of timing on inside "
        "information, and that the disclosures alleged to have been misleading "
        "had been drafted and reviewed by the company's general counsel and "
        "outside securities lawyers. The defense further argued that the company's "
        "subsequent management, in characterizing the payments as 'unauthorized,' "
        "had retroactive incentives to repudiate compensation decisions its "
        "predecessors had in fact made."
        "\n\nSTATISTICAL CONTEXT: White-collar prosecutions of named chief executives "
        "of large publicly traded companies are historically rare and have a "
        "conviction rate well below 60% at trial, in part because the central "
        "question intent is difficult to prove beyond a reasonable doubt against "
        "defendants whose conduct passed through layers of corporate process. The "
        "case was tried during a period of intense public attention to corporate "
        "scandal, in the immediate aftermath of several major accounting collapses, "
        "and was widely characterized in the media as a referendum on executive "
        "excess. After approximately eleven days of deliberation by the twelve-"
        "person jury, the trial judge declared a mistrial. The deliberations had "
        "produced what the foreperson later described as a near-unanimous lean "
        "toward conviction, but had been disrupted in their final days after a "
        "newspaper printed the name of an individual juror who had appeared to "
        "be holding out against conviction, after which that juror reported "
        "receiving a threatening communication from outside the courtroom. The "
        "judge found the external pressure made continued deliberation untenable "
        "and declared the mistrial without further verdict. A retrial commenced "
        "in 2005 with a different jury and resulted in convictions on twenty-two "
        "of twenty-three counts and a sentence of eight to twenty-five years in "
        "state prison; the defendant served approximately six and a half years "
        "before being granted parole."
    ),
)

CASES = {
    "tax_evasion": TAX_EVASION,
    "perjury": PERJURY,
    "defamation": DEFAMATION,
    "fraud": FRAUD,
    "larceny": LARCENY,
}
